on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # ⬅️ Explicitly render the site so _site/ exists
      - name: Render site
        run: quarto render

      # ⬅️ Publish the rendered _site folder to gh-pages
      - name: Publish to gh-pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
